import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body className="font-VazirMatn-Regular text-foreground min-h-[2000px] h-full"
      >
      <Header/>
        {children}
      </body>
    </html>
  );
}
